#!/usr/bin/env bash
# Bash script to configure Nginx so that its 
#HTTP response contains a custom header: web-01 and web-02
sudo apt update
sudo apt upgrade -y
sudo apt install nginx -y

sudo ufw allow 'Nginx HTTP'
sudo ufw allow 22

echo "Welcome to PharmakariosTechHub!." > /var/www/html/index.html

touch /var/www/html/custom_404.html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /var/www/html;
     index       index.html index.htm;
     add_header X-Served-By $HOSTNAME;
     location /redirect_me {
        return 301 https://twitter.com/ng_search;
    }
    error_page 404 /custom_404.html;
    location /custom_404 {
      root /var/www/html;
      internal;
    }
}
" > /etc/nginx/sites-available/default
sudo service nginx restart
